"""db improvements for auth

Revision ID: 2d0a9d1f5524
Revises: 7e21c2ccbb41
Create Date: 2025-08-05 20:33:50.964885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0a9d1f5524'
down_revision: Union[str, Sequence[str], None] = '7e21c2ccbb41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email_verification_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email_verification_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
