"""auth fileds fixes

Revision ID: 7e21c2ccbb41
Revises: f131cbceaf87
Create Date: 2025-08-03 12:37:13.542527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e21c2ccbb41'
down_revision: Union[str, Sequence[str], None] = 'f131cbceaf87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_analytics_account_date'), table_name='analytics_data')
    op.drop_index(op.f('idx_analytics_type_date'), table_name='analytics_data')
    op.drop_constraint(op.f('unique_daily_analytics'), 'analytics_data', type_='unique')
    op.drop_index(op.f('idx_clip_score_format'), table_name='clip')
    op.drop_index(op.f('idx_clip_video_status'), table_name='clip')
    op.drop_index(op.f('idx_post_account_status'), table_name='post')
    op.drop_index(op.f('idx_post_performance'), table_name='post')
    op.drop_index(op.f('idx_post_scheduled'), table_name='post')
    op.add_column('user', sa.Column('account_lockout_expiry', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('idx_crt_at'), table_name='video')
    op.drop_index(op.f('indx_vid_prj_status'), table_name='video')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('indx_vid_prj_status'), 'video', ['project_id', 'status'], unique=False)
    op.create_index(op.f('idx_crt_at'), 'video', ['created_at'], unique=False)
    op.drop_column('user', 'account_lockout_expiry')
    op.create_index(op.f('idx_post_scheduled'), 'post', ['status', 'scheduled_at'], unique=False)
    op.create_index(op.f('idx_post_performance'), 'post', ['published_at', 'engagement_rate'], unique=False)
    op.create_index(op.f('idx_post_account_status'), 'post', ['account_id', 'status'], unique=False)
    op.create_index(op.f('idx_clip_video_status'), 'clip', ['video_id', 'status'], unique=False)
    op.create_index(op.f('idx_clip_score_format'), 'clip', ['ai_score', 'format'], unique=False)
    op.create_unique_constraint(op.f('unique_daily_analytics'), 'analytics_data', ['account_id', 'type', 'date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_analytics_type_date'), 'analytics_data', ['type', 'date'], unique=False)
    op.create_index(op.f('idx_analytics_account_date'), 'analytics_data', ['account_id', 'date'], unique=False)
    # ### end Alembic commands ###
